name: A5
channels:
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud//pytorch/
# - pytorch
# - menpo
# - defaults
dependencies:
- jupyter
- matplotlib
- python=3.5
- scikit-learn
- scikit-image
- scipy
- numpy
- opencv3
- cyvlfeat
- pytorch-cpu
- torchvision-cpu
- pip
- pip:
  - visdom
- pyyaml
